language: python
python:
  - '2.7'
  - '3.4'

services:
  - postgresql

env:
  - DATABASE_URL=postgres:///learning_journal

before_script:
  - psql -c "create database learning_journal;" -U postgres

# command to install dependencies
install:
  - pip install -e .
  - pip install -e .[testing]

# command to run tests
script: 
  - tox

# safelist
branches:
  only:
  - security

after_success:
  - coveralls
